Added Water Sever 17
SpykerNZ/one-pace-for-plex pull request #29
Opened 2024-02-19 17:17 UTC by trulow

## Describe your changes

## Checklist for submitting new .nfo files
- [x] I have removed the old .nfo files that are being replaced
- [x] I have validated that the new .nfo file works correctly in Plex
- [x] I have updated the README, fixing the list of current missing episodes
- [x] I have modified exceptions.json, removing any exceptions no longer required

2024-02-20 18:53 UTC, cawnj commented
@trulow Thanks for the change!

With the nfo file, the aired date and duration in seconds are incorrect.

The aired date should be the release date on onepace.net - for this ep it's `Released on: 2/17/2024`
And for the duration in seconds, run the file through tinyMediaManager to get the correct file/media info (this makes sure all the info like audio tracks, subtitle languages, etc. are correct - but also the duration). For this ep the value should be `1509`

Everything else though looks perfect to me!

2024-02-28 19:18 UTC, trulow commented
Updated and also added episode 18 as well

2024-02-28 19:29 UTC, cawnj requested changes
Added one comment regarding E17. Everything else looks good, and E18 also looks good. Ty @trulow 🙏

2024-02-28 19:29 UTC, cawnj commented on One Pace/Season 18/One Pace - S18E17 - Sogeking.nfo
> +  <aired>2024-02-16</aired>
This should be `2024-02-17` as displayed on [onepace.net/watch](https://www.onepace.net/watch) in the episode description

2024-02-28 20:05 UTC, trulow commented
Dated updated

2024-02-28 20:59 UTC, cawnj approved these changes
Ty, LGTM!

2024-02-28 20:59 UTC, merged